"use server"

import { createAdminClient } from "@/lib/supabase/admin"
import { fullApplicationSchema } from "@/lib/validation/schemas"
import { bucketForDocType } from "@/lib/constants"
import { writeAudit } from "@/lib/audit"

export type SubmitResult =
  | { ok: true; reference: string }
  | { ok: false; error: string }

/**
 * Server-side application submission. Validates the full payload with Zod
 * (never trusting the client), writes all normalized rows using the service
 * role, finalizes uploaded documents into the reference-number path, and
 * records status history + an audit entry.
 */
export async function submitApplication(payload: unknown): Promise<SubmitResult> {
  const parsed = fullApplicationSchema.safeParse(payload)
  if (!parsed.success) {
    return { ok: false, error: "validation" }
  }
  const data = parsed.data
  const admin = createAdminClient()

  // 1. Root application (reference_number generated by DB default).
  const { data: app, error: appErr } = await admin
    .from("oes_applications")
    .insert({
      status: "submitted",
      primary_phone: data.personal.contact_number,
      applicant_name: data.personal.full_name,
    })
    .select("id, reference_number")
    .single()

  if (appErr || !app) {
    console.error("application insert failed", appErr)
    return { ok: false, error: "server" }
  }

  const appId = app.id
  const reference = app.reference_number

  // 2. Child detail rows.
  const childInserts = [
    admin.from("oes_personal_details").insert({ application_id: appId, ...data.personal }),
    admin.from("oes_education_details").insert({
      application_id: appId,
      ...data.education,
      has_scholarship:
        data.education.has_scholarship ||
        !!data.education.scholarship_details?.trim(),
    }),
    admin.from("oes_family_details").insert({ application_id: appId, ...data.family }),
    admin.from("oes_impairment_details").insert({ application_id: appId, ...data.impairment }),
    admin.from("oes_residence_details").insert({ application_id: appId, ...data.residence }),
    ...(data.siblings.siblings.length > 0
      ? [
          admin.from("oes_siblings").insert(
            data.siblings.siblings.map((s) => ({ application_id: appId, ...s }))
          ),
        ]
      : []),
  ]

  const results = await Promise.all(childInserts)
  const childError = results.find((r) => r.error)
  if (childError) {
    console.error("child insert failed", childError.error)
    // Roll back the root record so we don't leave an orphan.
    await admin.from("oes_applications").delete().eq("id", appId)
    return { ok: false, error: "server" }
  }

  // 3. Finalize documents: move from draft path to reference path, record rows.
  for (const doc of data.documents) {
    const bucket = doc.bucket || bucketForDocType(doc.document_type)
    const finalPath = `applications/${reference}/${doc.document_type}/${
      doc.file_name ?? "file"
    }`
    try {
      if (doc.path !== finalPath) {
        await admin.storage.from(bucket).move(doc.path, finalPath)
      }
    } catch (e) {
      // Non-fatal: keep original path if the move fails.
      console.error("document move failed", e)
    }
    const storedPath = await pathExists(admin, bucket, finalPath)
      ? finalPath
      : doc.path
    await admin.from("oes_documents").insert({
      application_id: appId,
      document_type: doc.document_type,
      bucket,
      path: storedPath,
      file_name: doc.file_name ?? null,
      mime_type: doc.mime_type ?? null,
      size_bytes: doc.size_bytes ?? null,
    })
  }

  // 4. Initial status history.
  await admin.from("oes_application_status_history").insert({
    application_id: appId,
    from_status: null,
    to_status: "submitted",
    note: "Application submitted",
  })

  // 5. Audit.
  await writeAudit({
    action: "application.submitted",
    entity: "application",
    entityId: appId,
    details: { reference },
  })

  return { ok: true, reference }
}

async function pathExists(
  admin: ReturnType<typeof createAdminClient>,
  bucket: string,
  fullPath: string
): Promise<boolean> {
  const idx = fullPath.lastIndexOf("/")
  const dir = fullPath.slice(0, idx)
  const name = fullPath.slice(idx + 1)
  const { data } = await admin.storage.from(bucket).list(dir, { search: name })
  return !!data?.some((f) => f.name === name)
}
